global
  scrape_interval 15s
  evaluation_interval 15s

alerting
  alertmanagers
  - static_configs
    - targets
      # - alertmanager9093

rule_files
  # - first_rules.yml
  # - second_rules.yml

scrape_configs
  - job_name 'kubernetes-apiservers'
    kubernetes_sd_configs
    - role endpoints
    scheme https
    tls_config
      ca_file varrunsecretskubernetes.ioserviceaccountca.crt
    bearer_token_file varrunsecretskubernetes.ioserviceaccounttoken
    relabel_configs
    - source_labels [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action keep
      regex default;kubernetes;https

  - job_name 'kubernetes-nodes'
    scheme https
    tls_config
      ca_file varrunsecretskubernetes.ioserviceaccountca.crt
    bearer_token_file varrunsecretskubernetes.ioserviceaccounttoken
    kubernetes_sd_configs
    - role node
    relabel_configs
    - action labelmap
      regex __meta_kubernetes_node_label_(.+)
    - target_label __address__
      replacement kubernetes.default.svc443
    - source_labels [__meta_kubernetes_node_name]
      regex (.+)
      target_label __metrics_path__
      replacement apiv1nodes${1}proxymetrics

  - job_name 'kubernetes-pods'
    kubernetes_sd_configs
    - role pod
    relabel_configs
    - source_labels [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action keep
      regex true
    - source_labels [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action replace
      target_label __metrics_path__
      regex (.+)
    - source_labels [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action replace
      regex ([^]+)(d+);(d+)
      replacement $1$2
      target_label __address__
    - action labelmap
      regex __meta_kubernetes_pod_label_(.+)
    - source_labels [__meta_kubernetes_namespace]
      action replace
      target_label kubernetes_namespace
    - source_labels [__meta_kubernetes_pod_name]
      action replace
      target_label kubernetes_pod_name

  - job_name 'gestion-stage-app'
    metrics_path 'actuatorprometheus'
    kubernetes_sd_configs
    - role service
    relabel_configs
    - source_labels [__meta_kubernetes_service_label_app]
      regex gestion-stage
      action keep