apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-stage-deployment
  labels:
    app: gestion-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestion-stage
  template:
    metadata:
      labels:
        app: gestion-stage
    spec:
      containers:
      - name: gestion-stage
        image: mehdichoukri10/gestion-stage:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"